name: Excel to Markdown
on: push                               # ワークフローのトリガー(今回はpush)

jobs:
  excel-to-markdown:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl tabulate

      - name: Convert Excel to Markdown
        id: convert
        run: |
          # Save the result to a temporary file
          python .github/scripts/convert_excel_to_markdown.py $GITHUB_WORKSPACE/Sample.xlsx "Sheet1" > $RUNNER_TEMP/table.md
          cat $RUNNER_TEMP/table.md

      - name: Update Sample.md
        run: |
          python .github/scripts/update_sample_md.py $RUNNER_TEMP/table.md "# Sample.md" $GITHUB_WORKSPACE/Sample.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Sample.md
          
          # If nothing to commit, then exit
          git diff --quiet && exit 0

          # Commit and push changes
          git commit -m "Update Sample.md with Excel conversion result"
          git push
